### ISSUE TITLE
Unable to create new own branch

### ISSUE THREAD

**Issue by ipotapov** [githubteacher/everyone-june-2016#187]
Have problems with creating branch.
Github does not show option to "create branch" when I clicked "master" and started to type in 
(see screenshot below)

![github_create_branch](https://cloud.githubusercontent.com/assets/3835860/16238821/0b87d6f8-37b0-11e6-9cbd-b573a3dff244.jpg)

**Comment by hectorsector** [comment]
@ipotapov make sure you've commented on Issue #2 to be added as a collaborator, it's necessary to add a branch.

I'm closing this issue but feel free to continue chatting with us in the Gitter room: https://gitter.im/githubteacher/everyone-june-2016
