### ISSUE TITLE
Will we be shown how to use Github desktop?

### ISSUE THREAD

**Issue by TomBurg** [githubteacher/everyone-june-2016#192]
@githubteacher 

I am logged in with the web browser - but how does GitHub Desktop work?  Is it standalone?

**Comment by hectorsector** [comment]
@TomBurg yes, we'll be using GitHub Desktop this hour. Stay tuned. I'm closing this issue but if you'd like to continue to chat with us you can do so in the Gitter chat room https://gitter.im/githubteacher/everyone-june-2016

**Comment by johnborroughs** [comment]
hi
