### ISSUE TITLE
Please comment here to be added as a collaborator!

### ISSUE THREAD

**Issue by githubteacher** [githubteacher/everyone-june-2016#2]
There is a script running in the background that will automatically add you as a collaborator when you comment. 

This way, you will have special access for activities in this course.

If you're interested, you can find the script [here](https://github.com/github/training-utils). It's open source! 🎉

**Comment by GMartinez-Sisti** [comment]
Hi

**Comment by dany-phantom** [comment]
Heya :dancer:

**Comment by jleclerc-processia** [comment]
thanks

**Comment by doppeldimmykumont** [comment]
Hello! Hello! 👋

**Comment by PepMorales** [comment]
Hi

**Comment by tstone92** [comment]
hey hey!

**Comment by robb1891** [comment]
Hi!

**Comment by matteocellucci** [comment]
Hello 🍶

**Comment by sureshpvja** [comment]
Hi

**Comment by mark-gonzalez** [comment]
Hello there

**Comment by reedal** [comment]
hello

**Comment by garycentric** [comment]
Hello from Seattle.

**Comment by JimRoyal** [comment]
Nice to see Macs used in a dev environment.

**Comment by alexpribm** [comment]
Hi there :)

**Comment by WilliamRClark** [comment]
You can trust me!  I'm not like the others.

**Comment by Redfire2001** [comment]
Cheers :beer:

**Comment by David-Gehart** [comment]
Hello

**Comment by smitley** [comment]
Hello

**Comment by FrieseWoudloper** [comment]
Hi

**Comment by cobrien-dev** [comment]
test comment, please ignore

**Comment by sathya-ghub** [comment]
Hello

**Comment by chitch** [comment]
Hi, please add me as a collaborator

**Comment by smithmmf** [comment]
Hello folks

**Comment by ghost** [comment]
Hi

**Comment by MrTimms** [comment]
Hi

**Comment by ssd008** [comment]
Hi

**Comment by guramipal** [comment]
Hello

**Comment by boppana** [comment]
Hi

**Comment by belcomps** [comment]
Hello

**Comment by jdavis1998** [comment]
Hello

**Comment by swong888** [comment]
Hello

**Comment by GaurangSinghal** [comment]
hello

**Comment by sproutsibm** [comment]
Hi

**Comment by igalvan** [comment]
hi

**Comment by mlevine2000** [comment]
Hello

**Comment by pgrech98** [comment]
Hello

**Comment by mcscript2** [comment]
Good Morning

**Comment by kathrynpwells** [comment]
Hi! Carlsbad here :+1:

**Comment by pbeaudry-processia** [comment]
hello

**Comment by trapxrist** [comment]
hello

**Comment by jleclerc-processia** [comment]
is it recorded ?

**Comment by vvpriya** [comment]
Good Morning!

**Comment by miltatibm** [comment]
Hello Thank you for doing this webinar!!

**Comment by n0rbs** [comment]
- hello :)

**Comment by HollyMJones** [comment]
hello hello! :+1:

**Comment by fuixx217** [comment]
hey!

**Comment by vvadl-Belfast** [comment]
Hi

**Comment by FerminOcon** [comment]
hello

**Comment by Framme** [comment]
Hi from Mexico!

**Comment by ssheru** [comment]
Hi

**Comment by mtnstim** [comment]
hi

**Comment by ghost** [comment]
hello

**Comment by cswartzentruber** [comment]
hello

**Comment by scathaig** [comment]
hello world!

**Comment by chuckp01** [comment]
Hello !

**Comment by Govin-lala** [comment]
HI

**Comment by charglen** [comment]
hello from DC

**Comment by pritish-devurkar** [comment]
Hello from Boston!

**Comment by dbriand** [comment]
Hey

**Comment by mcscript2** [comment]
hi

**Comment by pgrech98** [comment]
From RBC

**Comment by UzemaJeena** [comment]
Hello from Montreal!

**Comment by smanthena** [comment]
Hi from Sangeeta

**Comment by nimmagadda19** [comment]
hello

**Comment by RameshKatkam** [comment]
Hello

**Comment by vvadl-Belfast** [comment]
Hellow

**Comment by ryanjsmith1980** [comment]
Hey

**Comment by ajith633** [comment]
hello

**Comment by RuchR** [comment]
hi

**Comment by pablomt** [comment]
hi

**Comment by joebaile** [comment]
Hello

**Comment by ghost** [comment]
hi

**Comment by ghost** [comment]
hello from Guadalajara, México,  please add me as collaborator

**Comment by dawncarpenter** [comment]
hi

**Comment by jdavis1998** [comment]
collab

**Comment by calvingerus** [comment]
Hello lets collaborate

**Comment by brendenbattle** [comment]
collab please

**Comment by chanlon27** [comment]
Hi

**Comment by atroe** [comment]
hello world

**Comment by benoraj** [comment]
Hello.

**Comment by githubteacher** [comment]
:tada: @GMartinez-Sisti, @dmahmalat, @jleclerc-processia, @doppelDimmykumont, @PepMorales, @tstone92, @robb1891, @matteocellucci, @suresh3192, @mark-gonzalez, @deereflow, @beneluxboy, @JimRoyal, @alexpribm, @WilliamRClark, @Redfire2001, @David-Gehart, @master-smit, @FrieseWoudloper, @cobrien-dev, @sathya-ghub, @chitch, @smithmmf, @SanthoshSubramaniam, @MrTimms, @ssd008, @guramipal, @boppana, @belcomps, @jdavis1998, @swong888, @GaurangSinghal, @sproutsibm, @igalvan, @mlevine2000, @pgrech98, @mcscript2, @kathrynpwells, @pbeaudry-processia, @trapxrist, @jleclerc-processia, @vvpriya, @miltatibm, @n0rbs, @HollyMJones, @fuixx217, @vvadl, @FerminOcon, @Framme, @ssheru, @mtnstim, @krishnan-mk, @cswartzentruber, @scathaig, @chuckp01, @Govin-lala, @charglen, @findpritz, @dbriand, @mcscript2, @pgrech98, @UzemaJeena, @smanthena, @nimmagadda19, @RameshKatkam, @vvadl, @ryanjsmith1980, @ajith633, @RuchR, @pablomt, @jbbinrtp, @webnewbie, @moyomendoza, @dawncarpenter, @jdavis1998, @calvingerus, @brendenbattle, and @chanlon27 are now  repository collaborators. :balloon:

**Comment by wintercl133** [comment]
hi

**Comment by tslenahan** [comment]
Hello

**Comment by gitalinoe** [comment]
Hi there

**Comment by mgatgit** [comment]
Hi

**Comment by Joezer** [comment]
howdy

**Comment by brendenbattle** [comment]
hi guys, what's the link to chat?

**Comment by jaitawatkuldeep** [comment]
hi

**Comment by cschlallstate** [comment]
hi

**Comment by githubteacher** [comment]
:tada: @atroe, @benoraj, @wintercl133, @tslenahan, @gitalinoe, @mgatgit, @Joezer, and @jaitawatkuldeep are now  repository collaborators. :balloon:

**Comment by smanthena** [comment]
hi

**Comment by Eli-Hayes** [comment]
Hi

**Comment by octaviomagana** [comment]
Hello

**Comment by githubteacher** [comment]
@halfaro1 What do you think?

**Comment by githubteacher** [comment]
:tada: @cschlallstate, @Eli-Hayes, and @octaviomagana are now  repository collaborators. :balloon:

**Comment by hectorsector** [comment]
@githubteacher nooooo!

**Comment by Ashok-Rodricks** [comment]
Hi

**Comment by jackief** [comment]
comment

**Comment by Apple-K** [comment]
Hi

**Comment by KevinPMason** [comment]
Comment

**Comment by githubteacher** [comment]
:tada: @halfaro1, @Ashok-Rodricks, @jackief, @Apple-K, and @KevinPMason are now  repository collaborators. :balloon:

**Comment by ghost** [comment]
HI finally worked out what to do!!

**Comment by githubteacher** [comment]
:tada: @Mawer is now a repository collaborator. :balloon:

**Comment by emirj** [comment]
hello

**Comment by GaurangSinghal** [comment]
hi

**Comment by githubteacher** [comment]
:tada: @emirj is now a repository collaborator. :balloon:

**Comment by marinafurman** [comment]
Hello I am Marina

**Comment by githubteacher** [comment]
:tada: @marinafurman is now a repository collaborator. :balloon:

**Comment by sarmatejas1006** [comment]
Hello I am Tejas! Hello Everyone :smile:

**Comment by githubteacher** [comment]
:tada: @sarmatejas1006 is now a repository collaborator. :balloon:

**Comment by fgratuito** [comment]
hello

**Comment by erinbenoit** [comment]
hi

**Comment by DSallGH1** [comment]
hi

**Comment by bsmith221** [comment]
hello

**Comment by Eli-Hayes** [comment]
Hi

**Comment by Rk2013** [comment]
hi

**Comment by sdwalker7** [comment]
hello

**Comment by TomBurg** [comment]
Late but still here

**Comment by pgrech98** [comment]
testing

**Comment by AbhinitMallick** [comment]
hi

**Comment by githubteacher** [comment]
:tada: @fgratuito, @erinbenoit, @DSallGH1, @bsmith221, @Rk2013, @sdwalker7, and @TomBurg are now  repository collaborators. :balloon:

**Comment by SarahWerner** [comment]
hello

**Comment by TerriLLBean** [comment]
Hello

**Comment by mcscript2** [comment]
collab

**Comment by mccue** [comment]
Add me!

**Comment by githubteacher** [comment]
:tada: @AbhinitMallick, @SarahWerner, @TerriLLBean, and @mccue are now  repository collaborators. :balloon:

**Comment by gabbyspg** [comment]
Hi :) :

**Comment by gopalthannir** [comment]
hi

**Comment by Deneli** [comment]
Guess I never did this

**Comment by githubteacher** [comment]
:tada: @gabbyspg, @gopalthannir, and @Deneli are now  repository collaborators. :balloon:

**Comment by Joezer** [comment]
adding

**Comment by sukhatri** [comment]
Hello

**Comment by githubteacher** [comment]
:tada: @sukhatri is now a repository collaborator. :balloon:

**Comment by dragonshiryu** [comment]
yo

**Comment by githubteacher** [comment]
:tada: @dragonshiryu is now a repository collaborator. :balloon:

**Comment by jerryguti** [comment]
jerryguti is commenting

**Comment by githubteacher** [comment]
:tada: @jerryguti is now a repository collaborator. :balloon:

**Comment by johnborroughs** [comment]
please add me

**Comment by githubteacher** [comment]
:tada: @johnborroughs is now a repository collaborator. :balloon:

**Comment by meisutanto** [comment]
Hello everyone!

**Comment by githubteacher** [comment]
:tada: @meisutanto is now a repository collaborator. :balloon:

**Comment by ipotapov** [comment]
Add comment to be able to create branch

**Comment by githubteacher** [comment]
:tada: @ipotapov is now a repository collaborator. :balloon:

**Comment by MikeSmith7** [comment]
Hi

**Comment by githubteacher** [comment]
:tada: @MikeSmith7 is now a repository collaborator. :balloon:

**Comment by gitalinoe** [comment]
Hi There

**Comment by llavelanet** [comment]
Looking for the best tapas bar in New York City

**Comment by githubteacher** [comment]
:tada: @ghost and @llavelanet are now  repository collaborators. :balloon:

**Comment by brianamarie** [comment]
Hello!

**Comment by hollenberry** [comment]
Mattstopsgettingsparkles

**Comment by githubteacher** [comment]
:tada: @hollenberry is now a repository collaborator. :balloon:

**Comment by sukhatri** [comment]
Was wondering if there is demo on line?

**Comment by stlpatd** [comment]
reviewing

**Comment by klrivers** [comment]
please add me
